import bcrypt from "bcryptjs";

const data = {
	users: [
		{
			name: "Gustavo",
			email: "admin@gmail.com",
			password: bcrypt.hashSync("123"),
			resetToken: "",
			isAdmin: true,
		},
		{
			name: "Customer",
			email: "customerr@gmail.com",
			password: bcrypt.hashSync("123"),
			resetToken: "",
			isAdmin: false,
		},
	],
	products: [
		{
			name: "Mate gourd with Alpaca finish",
			slug: "Mate gourd with Alpaca finish",
			price: 60,
			description:
				"Gourd mate hand wrapped and sewed in cow leather with alpaca finish around the opening.",
			image: "https://login.eltero.net/modules/products/uploads/product_1.jpeg",
			stock: 500,
			isDeleted: false,
			comments: [],
			category: "Mates",
			rating: 0,
			brand: "El Tero",
			numReviews: 0,
		},
		{
			name: "Mate gourd with alpaca colonial design.",
			slug: "Mate gourd with alpaca colonial design.",
			price: 65,
			description:
				"Gourd mate hand wrapped and sewed in cow leather. The alpaca finish around the opening has a chiseled Real design.",
			image: "https://login.eltero.net/modules/products/uploads/product_2.jpeg",
			stock: 0,
			isDeleted: false,
			comments: [],
			category: "Mates",
			rating: 0,
			brand: "El Tero",
			numReviews: 0,
		},
		{
			name: "Mate with alpaca finish real",
			slug: "Mate with alpaca finish real",
			price: 65,
			description: "Gourd mate hand wrapped and sewed in cow leather.",
			image: "https://login.eltero.net/modules/products/uploads/product_3.jpeg",
			stock: 500,
			isDeleted: false,
			comments: [],
			category: "Mates",
			rating: 0,
			brand: "El Tero",
			numReviews: 0,
		},
		{
			name: "Mate with alpaca finish Colonial",
			slug: "Mate with alpaca finish Colonial",
			price: 55,
			description:
				"Gourd mate with Alpaca opening with chiseled Colonial design.",
			image: "https://login.eltero.net/modules/products/uploads/product_5.jpeg",
			stock: 500,
			isDeleted: false,
			comments: [],
			category: "Mates",
			rating: 0,
			brand: "El Tero",
			numReviews: 0,
		},
		{
			name: "Mate with alpaca finish",
			slug: "Mate with alpaca finish",
			price: 50,
			description:
				"Gourd mate with alpaca finish around the opening. The mate comes with a stand base of cow leather.",
			image: "https://login.eltero.net/modules/products/uploads/product_6.jpeg",
			stock: 500,
			isDeleted: false,
			comments: [],
			category: "Mates",
			rating: 0,
			brand: "El Tero",
			numReviews: 0,
		},
		{
			name: "Yerbera 300g",
			slug: "Yerbera 300g",
			price: 75,
			description:
				"A Yerbera is a leather bag use to fill it with yerba mate. ",
			image:
				"https://login.eltero.net/modules/products/uploads/product_25.jpeg",
			stock: 50,
			isDeleted: false,
			comments: [],
			category: "Yerberas",
			rating: 0,
			brand: "El Tero",
			numReviews: 0,
		},
		{
			name: "Combo Rosillo",
			slug: "Combo Rosillo",
			price: 455,
			description:
				"This combo has a gourd mate hand wrapped and sewed in cow leather",
			image:
				"https://login.eltero.net/modules/products/uploads/product_26.jpeg",
			stock: 50,
			isDeleted: false,
			comments: [],
			category: "Combos",
			rating: 0,
			brand: "El Tero",
			numReviews: 0,
		},
		{
			name: "Combo 'Pampa'",
			slug: "Combo 'Pampa'",
			price: 500,
			description:
				"This combo has a gourd mate hand wrapped and sewed in cow leather.",
			image:
				"https://login.eltero.net/modules/products/uploads/product_31.jpeg",
			stock: 50,
			isDeleted: false,
			comments: [],
			category: "Combos",
			rating: 0,
			brand: "El Tero",
			numReviews: 0,
		},
		{
			name: "Corkscrew Hoja de Acanto",
			slug: "Corkscrew Hoja de Acanto",
			price: 150,
			description:
				"Our Corkscrew is made of Alpaca and quebracho colorado wood.",
			image: "https://login.eltero.net/modules/products/uploads/product_47.png",
			stock: 50,
			isDeleted: false,
			comments: [],
			category: "Corkscrew",
			rating: 0,
			brand: "El Tero",
			numReviews: 0,
		},
		{
			name: "Corkscrew Gallonado",
			slug: "Corkscrew Gallonado",
			price: 50,
			description:
				"Our Corkscrew is made of Alpaca and quebracho colorado wood. It comes in a wooden box with velveteen interiors.",
			image: "https://login.eltero.net/modules/products/uploads/product_48.png",
			stock: 50,
			isDeleted: false,
			comments: [],
			category: "Corkscrew",
			rating: 0,
			brand: "El Tero",
			numReviews: 0,
		},
		{
			name: "Set Sommelier",
			slug: "Set Sommelier",
			price: 150,
			description:
				"This set contains two bottle savers, two wine bottle collars.",
			image: "https://login.eltero.net/modules/products/uploads/product_49.png",
			stock: 50,
			isDeleted: false,
			comments: [],
			category: "Wine set",
			rating: 0,
			brand: "El Tero",
			numReviews: 0,
		},
		{
			name: "Bottle saver and wine bottle collar set",
			slug: "Bottle saver and wine bottle collar set",
			price: 30,
			description:
				"This set comes with an alpaca wine bottle collar that has, in it´s interior, a felt lined to avoid wine spilling.",
			image: "https://login.eltero.net/modules/products/uploads/product_51.png",
			stock: 50,
			isDeleted: false,
			comments: [],
			category: "Wine set",
			rating: 0,
			brand: "El Tero",
			numReviews: 0,
		},
		{
			name: "Carving set 'Vizcacha'",
			slug: "Carving set 'Vizcacha'",
			price: 90,
			description:
				"Set of stainless steel knife and fork with Alpaca hilt. It has exclusively handcrafted designs. Blade: 12 cm. Handle: 10. Knife: 22.",
			image: "https://login.eltero.net/modules/products/uploads/product_55.png",
			stock: 50,
			isDeleted: false,
			comments: [],
			category: "Knives",
			rating: 0,
			brand: "El Tero",
			numReviews: 0,
		},
		{
			name: "Carving set 'Sombra'",
			slug: "Carving set 'Sombra'",
			price: 350,
			description:
				"Set of stainless steel knife and fork with Alpaca hilt. It has exclusively handcrafted designs. Blade: 12 cm. Handle: 10. Knife: 22.",
			image: "https://login.eltero.net/modules/products/uploads/product_56.png",
			stock: 50,
			isDeleted: false,
			comments: [],
			category: "Knives",
			rating: 0,
			brand: "El Tero",
			numReviews: 0,
		},
		{
			name: "Bottle Saver Gallonado",
			slug: "Bottle Saver Gallonado",
			price: 1450,
			description:
				"Alpaca, also known as german silver, bottle saver with ﻿Gallonado motifs.",
			image:
				"https://login.eltero.net/modules/products/uploads/product_40.jpeg",
			stock: 50,
			isDeleted: false,
			comments: [],
			category: "Bottle saver",
			rating: 0,
			brand: "El Tero",
			numReviews: 0,
		},
	],
};

export default data;
